spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://43.140.197.15:3306/vote
      url: jdbc:mysql://localhost:3306/counselor_competition
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bluemsun.entity

server:
  port: 8080
